/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */
public class ThongTinCuaHang extends javax.swing.JFrame {

    /**
     * Creates new form ThongTinCuaHang
     */
    public ThongTinCuaHang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        btnTrangChu = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        btnQuanLyThuCung = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        btnQuanLyDonHang = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        btnQuanLyKhachHang = new javax.swing.JButton();
        jLabel41 = new javax.swing.JLabel();
        btnQuanLyNhanVien = new javax.swing.JButton();
        jLabel42 = new javax.swing.JLabel();
        btnBaoCao = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        btnQuayLai = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1240, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(246, 0, 1240, 29);

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhdoan/logo.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(161, 66, 66));
        jLabel36.setText("PetsHome");

        btnTrangChu.setBackground(new java.awt.Color(255, 153, 153));
        btnTrangChu.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnTrangChu.setForeground(new java.awt.Color(161, 66, 66));
        btnTrangChu.setText("Trang chủ");

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhdoan/trang chủ.png"))); // NOI18N
        jLabel37.setText("jLabel3");

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhdoan/thú cưng.png"))); // NOI18N
        jLabel38.setText("jLabel4");

        btnQuanLyThuCung.setBackground(new java.awt.Color(255, 153, 153));
        btnQuanLyThuCung.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnQuanLyThuCung.setForeground(new java.awt.Color(161, 66, 66));
        btnQuanLyThuCung.setText("Quản lý thú cưng");

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhdoan/đơn hàng.png"))); // NOI18N
        jLabel39.setText("jLabel5");

        btnQuanLyDonHang.setBackground(new java.awt.Color(255, 153, 153));
        btnQuanLyDonHang.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnQuanLyDonHang.setForeground(new java.awt.Color(161, 66, 66));
        btnQuanLyDonHang.setText("Quản lý đơn hàng");
        btnQuanLyDonHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyDonHangActionPerformed(evt);
            }
        });

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhdoan/khách hàng.png"))); // NOI18N
        jLabel40.setText("jLabel6");

        btnQuanLyKhachHang.setBackground(new java.awt.Color(253, 153, 153));
        btnQuanLyKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnQuanLyKhachHang.setForeground(new java.awt.Color(161, 66, 66));
        btnQuanLyKhachHang.setText("Quản lý khách hàng");

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhdoan/nhân viên.png"))); // NOI18N
        jLabel41.setText("jLabel7");

        btnQuanLyNhanVien.setBackground(new java.awt.Color(253, 153, 153));
        btnQuanLyNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnQuanLyNhanVien.setForeground(new java.awt.Color(161, 66, 66));
        btnQuanLyNhanVien.setText("Quản lý nhân viên");

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhdoan/báo cáo.png"))); // NOI18N
        jLabel42.setText("jLabel25");

        btnBaoCao.setBackground(new java.awt.Color(253, 153, 153));
        btnBaoCao.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        btnBaoCao.setForeground(new java.awt.Color(161, 66, 66));
        btnBaoCao.setText("Báo cáo");
        btnBaoCao.setPreferredSize(new java.awt.Dimension(81, 48));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(btnTrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel36)))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnQuanLyThuCung, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnQuanLyDonHang, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnQuanLyKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnQuanLyNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBaoCao, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel36)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(btnTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(btnQuanLyThuCung, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(btnQuanLyDonHang, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel40)
                    .addComponent(btnQuanLyKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(btnQuanLyNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(btnBaoCao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 802, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 269, 1545);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(161, 66, 66));
        jLabel1.setText("Thông tin chi tiết");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(680, 30, 802, 54);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(161, 66, 66));
        jLabel3.setText("Tên cửa hàng: PetsHome");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(340, 100, 220, 25);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel4.setText("<html>- 470  Trần Đại Nghĩa- Hòa Quý- Ngũ Hành Sơn- Đà Nẵng<br>- 24 Lê Duẩn- Trung Giang- Gio Linh- Quảng Trị</html>");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(350, 200, 390, 60);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(161, 66, 66));
        jLabel5.setText("Số điện thoại: ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(340, 270, 140, 40);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel6.setText(" petshome.24ite@vku.udn.dn");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(410, 340, 220, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel7.setText(" 7:00 AM- 20:00 PM");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(450, 426, 202, 20);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(161, 66, 66));
        jLabel8.setText("Địa chỉ:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(340, 170, 85, 25);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel9.setText("1900897623");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(470, 260, 86, 60);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(161, 66, 66));
        jLabel10.setText("Lịch sử:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(970, 110, 88, 25);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel11.setText("<html>PetsHome được thành lập vào năm 2025 với mục tiêu trở thành hệ thống cửa hàng thú cưng uy tín và chuyên nghiệp.<br>Bắt đầu từ một cửa hàng nhỏ, PetsHome dần mở rộng quy mô, phát triển các dịch vụ như cung cấp thú cưng, phụ kiện, chăm sóc và tư vấn sức khỏe. Với phương châm “Yêu thú cưng như người thân”, PetsHome không ngừng cải tiến để mang lại trải nghiệm tốt nhất cho khách hàng và vật nuôi.");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(1020, 140, 430, 154);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(161, 66, 66));
        jLabel12.setText("Tầm nhìn:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(970, 320, 100, 25);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel13.setText("<html>Biến mỗi thú cưng thành “ngôi sao” trong chính cuộc sống <br>của mình – khỏe mạnh, sạch sẽ và luôn được cưng chiều.");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(1020, 340, 400, 70);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(161, 66, 66));
        jLabel14.setText("Giá trị cốt lõi:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(970, 410, 140, 25);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(161, 66, 66));
        jLabel15.setText("Email:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(340, 340, 60, 30);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(161, 66, 66));
        jLabel16.setText("Giờ mở cửa:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(340, 410, 110, 50);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel17.setText("Chất lượng- Uy tín- Tận tâm.");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(1020, 450, 200, 21);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(161, 66, 66));
        jLabel18.setText("Tại sao nên tin tưởng lựa chọn PetsHome?");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(570, 510, 420, 27);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel19.setText("Đa dạng thú cưng đáng yêu.");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(680, 560, 200, 30);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel20.setText("Giá cả hợp lý.");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(680, 600, 130, 30);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel21.setText("Dịch vụ chăm sóc tận tâm.");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(680, 640, 200, 30);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel22.setText("Đội ngũ tư vấn chuyên nghiệp.");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(680, 680, 250, 21);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhdoan/đại chỉ.png"))); // NOI18N
        jPanel1.add(jLabel23);
        jLabel23.setBounds(280, 160, 60, 66);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhdoan/petsHome.png"))); // NOI18N
        jPanel1.add(jLabel24);
        jLabel24.setBounds(280, 90, 60, 50);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhdoan/SĐT.png"))); // NOI18N
        jPanel1.add(jLabel25);
        jLabel25.setBounds(280, 270, 50, 40);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhdoan/Mail.png"))); // NOI18N
        jPanel1.add(jLabel26);
        jLabel26.setBounds(280, 340, 102, 40);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhdoan/Giờ.png"))); // NOI18N
        jPanel1.add(jLabel27);
        jLabel27.setBounds(290, 410, 99, 40);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhdoan/lịch sử.png"))); // NOI18N
        jPanel1.add(jLabel28);
        jLabel28.setBounds(910, 100, 102, 50);

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhdoan/tầm nhìn.png"))); // NOI18N
        jPanel1.add(jLabel29);
        jLabel29.setBounds(910, 310, 103, 40);

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhdoan/giá trị cốt lõi.png"))); // NOI18N
        jPanel1.add(jLabel30);
        jLabel30.setBounds(920, 400, 97, 50);

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhdoan/lý do.png"))); // NOI18N
        jPanel1.add(jLabel31);
        jLabel31.setBounds(620, 670, 50, 50);

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhdoan/lý do.png"))); // NOI18N
        jPanel1.add(jLabel32);
        jLabel32.setBounds(620, 550, 50, 40);

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhdoan/lý do.png"))); // NOI18N
        jPanel1.add(jLabel33);
        jLabel33.setBounds(620, 590, 50, 40);

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhdoan/lý do.png"))); // NOI18N
        jPanel1.add(jLabel34);
        jLabel34.setBounds(620, 630, 50, 40);

        btnQuayLai.setBackground(new java.awt.Color(255, 153, 153));
        btnQuayLai.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnQuayLai.setForeground(new java.awt.Color(161, 66, 66));
        btnQuayLai.setText("Quay lại");
        btnQuayLai.setPreferredSize(new java.awt.Dimension(89, 30));
        jPanel1.add(btnQuayLai);
        btnQuayLai.setBounds(1170, 710, 100, 30);

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhdoan/quay lại.png"))); // NOI18N
        jLabel35.setText("jLabel35");
        jPanel1.add(jLabel35);
        jLabel35.setBounds(1140, 710, 30, 27);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1504, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuanLyDonHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyDonHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuanLyDonHangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongTinCuaHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongTinCuaHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongTinCuaHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongTinCuaHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongTinCuaHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBaoCao;
    private javax.swing.JButton btnQuanLyDonHang;
    private javax.swing.JButton btnQuanLyKhachHang;
    private javax.swing.JButton btnQuanLyNhanVien;
    private javax.swing.JButton btnQuanLyThuCung;
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnTrangChu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
